plugins {
    id 'com.android.application'
}

android {
    namespace 'com.nadidstudio.swiftpay'
    compileSdk 36

    defaultConfig {
        applicationId 'com.nadidstudio.swiftpay'
        minSdk 26
        targetSdk 36
        versionCode 10
        versionName '2.0.0-native'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        debug { minifyEnabled false }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    packaging { resources { excludes += ['/META-INF/{AL2.0,LGPL2.1}'] } }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.core:core:1.17.0'
}
